dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0
  - aave/protocol-v2@aave-v2-asset-listing
  - Uniswap/v3-core@1.0.0
  # - Uniswap/v2-core@1.0.1
  - Uniswap/v3-periphery@1.3.0
  - Uniswap/v2-periphery@1.0.0-beta.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
      - '@aave=aave/protocol-v2@aave-v2-asset-listing'
      - '@uniswap3core=Uniswap/v3-core@1.0.0'
      # - '@uniswap2core=Uniswap/v2-core@1.0.1'
      - '@uniswap3periphery=Uniswap/v3-periphery@1.3.0'
      - '@uniswap2periphery=Uniswap/v2-periphery@1.0.0-beta.0'
dotenv: .env
networks:
  default: mainnet-fork-dev
  # https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
  mainnet:
    aave-addresses-provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth-token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    eth-token: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
    dai-token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    uniswap-router-v3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    uniswap-router-v2-02: "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"
    verify: True
  kovan:
    aave-addresses-provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    weth-token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    eth-token: ""
    dai-token: "0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD"
    verify: True
  # mainnet
  mainnet-fork-dev:
    aave-addresses-provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth-token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    eth-token: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
    dai-token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    uniswap-router-v3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    uniswap-router-v2-02: "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  bad_actor: ${BAD_ACTOR}